---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana
  labels:
    name: grafana
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: '6.x.x'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1
