apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-grafana
  annotations:
    cert-manager.io/issuer: "letsencrypt-staging"
    kubernetes.io/ingress.class: "nginx"
spec:
  # ingressClassName: nginx
  rules:
    - host: grafana.heaton.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 80
  tls:
    - hosts:
        - grafana.heaton.dev
      secretName: grafana-heaton-dev
