apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: grafana
namespace: grafana
resources:
  # - cert.yaml
  - ingress.yaml
  - namespace.yaml
  - release.yaml
  - source.yaml
