apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: heaton.dev-cert
  namespace: nginx-ingress
spec:
  secretName: heaton.dev-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - heaton.dev
  dnsNames:
    - "*.heaton.dev"
  issuerRef:
    name: letsencrypt-staging
    kind: Issuer
    group: cert-manager.io
  privateKey:
    rotationPolicy: Always
