---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: gke-ingress
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx-ingress
      version: '0.15.x'
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
        namespace: nginx-ingress
      interval: 1m
  values:
    replicaCount: 1
