apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx-ingress
      version: '0.15.x'
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
        namespace: nginx-ingress
      interval: 1m
  values:
    controller:
      service:
        # Value derrived from gke-ingress-regional
        loadBalancerIP: 34.22.255.106
    replicaCount: 1
    resources:
      limits:
        cpu: 0.5
        memory: 512Mi
      requests:
        cpu: 0.25
        memory: 512Mi
