---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx-ingress
      version: '0.15.x'
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
        namespace: nginx-ingress
      interval: 1m
  values:
    controller:
      service:
        loadBalancerIP: gke-ingress
    replicaCount: 1
