---
# This file is a patch that is applied to the base Helm chart. It adds the client.lifecycle.config.k8s.io/mutation: ignore annotation to all Deployments in the base directory.
apiVersion: apps/v1
kind: Deployment
metadata:
 name: any
 annotations:
   client.lifecycle.config.k8s.io/mutation: ignore
