apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfo
      version: '>5.0.0'
  interval: 1m0s
  releaseName: podinfo
  values:
    replicas: 1
    resources:
      limits:
        cpu: 0.5
        memory: 512Mi
      requests:
        cpu: 0.25
        memory: 512Mi
