apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: noreply@heaton.dev
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: noreply@heaton.dev
            apiKeySecretRef:
              name: cloudflare-apikey-secret
              key: apikey
        selector:
          matchLabels:
            "use-cloudflare-solver": "true"
